#/CYGNO/pathtocad /nfs/cygno/geometry/lime/

#CYGNO SHIELD
#define the experiment location:
/CYGNO/lab/select NoCave

#define if the geometry of the shielding is Full or NoShield
/CYGNO/shield/select FullShield
/CYGNO/shield/thick0 1 cm
/CYGNO/shield/thick1 1 cm
/CYGNO/shield/thick2 100 cm
/CYGNO/shield/thick3 10 cm
/CYGNO/shield/mat0 Air
/CYGNO/shield/mat1 Air
/CYGNO/shield/mat2 Air
/CYGNO/shield/mat3 Air

#define fraction of He and CF4 in the sensitive gas
/CYGNO/gas/frac_He 0.6
/CYGNO/gas/frac_CF4 0.4

# FINALLY ISSUE THE GEOMETRY UPDATE
/CYGNO/updateGeo
####



# GENERATION OF RADIOACTIVE PARTICLES
# define particle or ion 
/gps/particle neutron
# define energy (set 0 for radioactive decaying nuclei)

/gps/position 0. 30. 0. cm
/gps/ang/type iso
/gps/ene/type User
/gps/hist/type energy

/gps/hist/point    0.         0. 
/gps/hist/point    0.215686   0.0143987   
/gps/hist/point    0.431373    0.0333861
/gps/hist/point    0.647059    0.0312975
/gps/hist/point    0.862745    0.0282595
/gps/hist/point    1.07843     0.0250316
/gps/hist/point    1.29412    0.0214241
/gps/hist/point    1.5098     0.0199051
/gps/hist/point    1.72549    0.0175316
/gps/hist/point    1.94118    0.0191456
/gps/hist/point    2.15686    0.0222785
/gps/hist/point    2.37255    0.0214241
/gps/hist/point    2.58824    0.0224684
/gps/hist/point    2.80392    0.0228481
/gps/hist/point    3.01961    0.0293987
/gps/hist/point    3.23529    0.0354747
/gps/hist/point    3.45098    0.0368038
/gps/hist/point    3.66667    0.0347152
/gps/hist/point    3.88235    0.0306329
/gps/hist/point    4.09804    0.0300633
/gps/hist/point    4.31373    0.0268354
/gps/hist/point    4.52941    0.0286392
/gps/hist/point    4.7451     0.0316772
/gps/hist/point    4.96078   0.0308228
/gps/hist/point    5.17647    0.0332911
/gps/hist/point    5.39216    0.030443
/gps/hist/point    5.60784    0.0275
/gps/hist/point    5.82353    0.0234177
/gps/hist/point    6.03922    0.0206646
/gps/hist/point    6.2549     0.0181013
/gps/hist/point    6.47059   0.0176266
/gps/hist/point    6.68627    0.0204747
/gps/hist/point    6.90196    0.0182911
/gps/hist/point    7.11765    0.0162025
/gps/hist/point    7.33333    0.0168671
/gps/hist/point    7.54902    0.0187658
/gps/hist/point    7.76471    0.018481
/gps/hist/point    7.98039    0.017057
/gps/hist/point    8.19608    0.0143987
/gps/hist/point    8.41176    0.00974684
/gps/hist/point    8.62745    0.00651899
/gps/hist/point    8.84314    0.00433544
/gps/hist/point    9.05882    0.00367089
/gps/hist/point    9.27451    0.00386076
/gps/hist/point    9.4902     0.005
/gps/hist/point    9.70588   0.00623418
/gps/hist/point    9.92157    0.00556962
/gps/hist/point    10.1373    0.00462025
/gps/hist/point    10.3529    0.00367089
/gps/hist/point    10.5686    0.00281646
/gps/hist/point    10.7843    0.00148734
/gps/hist/point    11         0.000348101

/process/eLoss/StepFunction 0.001 0.01 mm
/CYGNO/stepmax 0.1 mm

#
#Save only events that pass that have hits in the sensitive gas
/CYGNO/cutoutfile 0
/CYGNO/save_hits_branches 1
/CYGNO/registeron 0
#
/run/initialize
#change these for debug
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/CYGNO/reportingfrequency 1000
#Output file name
/CYGNO/outfile test_neutrons_AmBe
/random/setSeeds 575841909 838392975
#/process/em/deexcitationIgnoreCut true

# define number of events to be generated
/run/beamOn 10000
