/CYGNO/pathtocad ../geometry/lime_new/

#CYGNO SHIELD
#define the experiment location:
/CYGNO/lab/select NoCave

#define if the geometry of the shielding is Full or NoShield
/CYGNO/shield/select AmBe
/CYGNO/shield/thick0 0 cm
/CYGNO/shield/thick1 0 cm
/CYGNO/shield/thick2 0 cm
/CYGNO/shield/thick3 0 cm
/CYGNO/shield/mat0 Air
/CYGNO/shield/mat1 Air
/CYGNO/shield/mat2 Air
/CYGNO/shield/mat3 Air

#define fraction of He and CF4 in the sensitive gas
/CYGNO/gas/frac_He 0.6
/CYGNO/gas/frac_CF4 0.4

# FINALLY ISSUE THE GEOMETRY UPDATE
/CYGNO/updateGeo
####
# GENERATION OF TRACKS
/CYGNO/generator/setGenerator txt_list
/CYGNO/generator/setInputFile ../LIME-MC/input_distribution/AmBe_input.txt

/process/eLoss/StepFunction 0.001 0.01 mm
/CYGNO/stepmax 0.1 mm

#
#Save only events that pass that have hits in the sensitive gas
/CYGNO/cutoutfile 0
/CYGNO/save_hits_branches 1
/CYGNO/registeron 1
#

/run/initialize
#change these for debug
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/CYGNO/reportingfrequency 10
#Output file name
/CYGNO/outfile test_digi_AmBe
/random/setSeeds 575841909 838392975
#/process/em/deexcitationIgnoreCut true

/run/beamOn 1394

