/CYGNO/pathtocad lime_new

#CYGNO SHIELD
#define the experiment location:
/CYGNO/lab/select NoCave

#define if the geometry of the shielding is Full or NoShield
/CYGNO/shield/select LIMEShield
/CYGNO/shield/thick0 0 cm
/CYGNO/shield/thick1 0 cm
/CYGNO/shield/thick2 0 cm
/CYGNO/shield/thick3 0 cm
/CYGNO/shield/mat0 Air 
/CYGNO/shield/mat1 Air
/CYGNO/shield/mat2 Air
/CYGNO/shield/mat3 Air


#define fraction of He and CF4 in the sensitive gas
/CYGNO/gas/frac_He 0.6
/CYGNO/gas/frac_CF4 0.4

# FINALLY ISSUE THE GEOMETRY UPDATE
/CYGNO/updateGeo
####

# GENERATION of particles
/gps/particle neutron
/gps/pos/type Surface
/gps/pos/shape Para

#from shield2:
#/gps/pos/centre 0.2 0.1 0. m
#/gps/pos/halfx 1.401 m 
#/gps/pos/halfy 1.001 m
#/gps/pos/halfz 1.051 m

#from shield3:
/gps/pos/centre 0.2 0.1 0. m
/gps/pos/halfx 0.851 m 
/gps/pos/halfy 0.476 m
/gps/pos/halfz 0.476 m

#from airbox:
#/gps/pos/centre 0.08 0.05 0. m
#/gps/pos/halfx 0.551 m 
#/gps/pos/halfy 0.301 m
#/gps/pos/halfz 0.276 m

# set the focusing point, default is (0, 0, 0)
#/gps/ang/type iso


/gps/ene/type User
/gps/hist/type energy
##FIXME: check normalization
#######      energy[MeV]  n/keV/cm2
/gps/hist/point 0	0
/gps/hist/point 0.001	1.81186e-06
/gps/hist/point 0.005	7.75105e-10
/gps/hist/point 0.01	1.00554e-09
/gps/hist/point 0.03	4.90202e-09
/gps/hist/point 0.05	3.93837e-09
/gps/hist/point 0.1	1.00973e-08
/gps/hist/point 0.5	8.03596e-08
/gps/hist/point 1	9.84593e-08
/gps/hist/point 2	2.8438e-07
/gps/hist/point 3	1.81982e-07
/gps/hist/point 4	9.15462e-08
/gps/hist/point 6	9.84384e-08
/gps/hist/point 10	1.8016e-09
/gps/hist/point 50	6.28464e-11
/gps/hist/point 100	4.18976e-11
/gps/hist/point 200	4.18976e-11
/gps/hist/point 300	0
/gps/hist/point 400	0
/gps/hist/point 500	0
/gps/hist/point 1000	0
/gps/hist/point 2000	0

/gps/ang/type user

/gps/hist/type theta
/gps/hist/point 0	0
/gps/hist/point 0.1309	453
/gps/hist/point 0.261799	1493
/gps/hist/point 0.392699	2629
/gps/hist/point 0.523599	3882
/gps/hist/point 0.654498	4978
/gps/hist/point 0.785398	5951
/gps/hist/point 0.916298	6813
/gps/hist/point 1.0472	7477
/gps/hist/point 1.1781	7892
/gps/hist/point 1.309	7906
/gps/hist/point 1.4399	7490
/gps/hist/point 1.5708	6861
/gps/hist/point 1.7017	6885
/gps/hist/point 1.8326	7565
/gps/hist/point 1.9635	7829
/gps/hist/point 2.0944	7659
/gps/hist/point 2.22529	7570
/gps/hist/point 2.35619	6814
/gps/hist/point 2.48709	5876
/gps/hist/point 2.61799	5106
/gps/hist/point 2.74889	3795
/gps/hist/point 2.87979	2548
/gps/hist/point 3.01069	1508
/gps/hist/point 3.14159	459

/gps/hist/type phi
/gps/hist/point 0	0
/gps/hist/point 0.261799	4412
/gps/hist/point 0.523599	4903
/gps/hist/point 0.785398	5505
/gps/hist/point 1.0472	5819
/gps/hist/point 1.309	5780
/gps/hist/point 1.5708	5594
/gps/hist/point 1.8326	5609
/gps/hist/point 2.0944	5795
/gps/hist/point 2.35619	5759
/gps/hist/point 2.61799	5528
/gps/hist/point 2.87979	5067
/gps/hist/point 3.14159	4261
/gps/hist/point 3.40339	4284
/gps/hist/point 3.66519	5016
/gps/hist/point 3.92699	5402
/gps/hist/point 4.18879	5747
/gps/hist/point 4.45059	5730
/gps/hist/point 4.71239	5535
/gps/hist/point 4.97419	5670
/gps/hist/point 5.23599	5609
/gps/hist/point 5.49779	5721
/gps/hist/point 5.75959	5500
/gps/hist/point 6.02139	4876
/gps/hist/point 6.28319	4317



#Save only events that pass that have hits in the sensitive gas
/CYGNO/cutoutfile 0
/CYGNO/save_hits_branches 1
/CYGNO/registeron 0
#
/run/initialize
#change these for debug
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/CYGNO/reportingfrequency 1000
#Output file name
/CYGNO/outfile ext_neutron_test
/random/setSeeds 575841909 838392975
#/process/em/deexcitationIgnoreCut true

# define number of events to be generated
/run/beamOn 100000
