/CYGNO/pathtocad lime_new

#CYGNO SHIELD
#define the experiment location:
/CYGNO/lab/select NoCave

#define if the geometry of the shielding is Full or NoShield
/CYGNO/shield/select LIMEShield
/CYGNO/shield/thick0 0 cm
/CYGNO/shield/thick1 0 cm
/CYGNO/shield/thick2 0 cm
/CYGNO/shield/thick3 0 cm
/CYGNO/shield/mat0 Air 
/CYGNO/shield/mat1 Air
/CYGNO/shield/mat2 Air
/CYGNO/shield/mat3 Air


#define fraction of He and CF4 in the sensitive gas
/CYGNO/gas/frac_He 0.6
/CYGNO/gas/frac_CF4 0.4

# FINALLY ISSUE THE GEOMETRY UPDATE
/CYGNO/updateGeo
####

# GENERATION of particles
/gps/particle neutron
/gps/pos/type Surface
/gps/pos/shape Para
/gps/pos/centre 0.2 0.1 0. m

#from shield2:
#/gps/pos/halfx 1.4 m 
#/gps/pos/halfy 1.0 m
#/gps/pos/halfz 1.05 m
#from shield3:
#/gps/pos/halfx 0.85 m 
#/gps/pos/halfy 0.475 m
#/gps/pos/halfz 0.475 m
#from airbox:
/gps/pos/halfx 0.55 m 
/gps/pos/halfy 0.3 m
/gps/pos/halfz 0.275 m

# set the focusing point, default is (0, 0, 0)
/gps/ang/type iso


/gps/ene/type User
/gps/hist/type energy
##FIXME: check normalization
#######      energy[MeV]  n/keV/cm2
/gps/hist/point  0.0    0.000001800000   
/gps/hist/point  0.001  0.000001800000   
/gps/hist/point  0.005  0.000000000864
/gps/hist/point  0.010  0.000000001080
/gps/hist/point  0.030  0.000000004320
/gps/hist/point  0.050  0.000000004320
/gps/hist/point  0.10   0.000000010800
/gps/hist/point  0.50   0.000000086400
/gps/hist/point  1.0    0.000000108000
/gps/hist/point  2.0    0.000000316000
/gps/hist/point  3.0    0.000000208000
/gps/hist/point  4.0    0.000000108000
/gps/hist/point  6.0    0.000000116000
/gps/hist/point  10.0   0.000000002000
/gps/hist/point  50.0   0.000000000160
/gps/hist/point  100.   0.000000000100
/gps/hist/point  200.   0.000000000050
/gps/hist/point  300.   0.000000000020
/gps/hist/point  400.   0.000000000010
/gps/hist/point  500.   0.000000000006
/gps/hist/point  1000.  0.000000000009
/gps/hist/point  2000.  0.000000000004

#Save only events that pass that have hits in the sensitive gas
/CYGNO/cutoutfile 1
/CYGNO/save_hits_branches 0
/CYGNO/registeron 1
#
/run/initialize
#change these for debug
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/CYGNO/reportingfrequency 1000
#Output file name
/CYGNO/outfile ext_neutron_test
/random/setSeeds 575841909 838392975
#/process/em/deexcitationIgnoreCut true

# define number of events to be generated
/run/beamOn 100000
