/CYGNO/pathtocad lime_new

#CYGNO SHIELD
#define the experiment location:
/CYGNO/lab/select NoCave

#define if the geometry of the shielding is Full or NoShield
/CYGNO/shield/select LIMEShield
/CYGNO/shield/thick0 0 cm
/CYGNO/shield/thick1 0 cm
/CYGNO/shield/thick2 0 cm
/CYGNO/shield/thick3 0 cm
/CYGNO/shield/mat0 Air 
/CYGNO/shield/mat1 Air
/CYGNO/shield/mat2 Air
/CYGNO/shield/mat3 Air


#define fraction of He and CF4 in the sensitive gas
/CYGNO/gas/frac_He 0.6
/CYGNO/gas/frac_CF4 0.4

# FINALLY ISSUE THE GEOMETRY UPDATE
/CYGNO/updateGeo
####

# GENERATION of particles
/gps/particle neutron
/gps/pos/type Surface
/gps/pos/shape Para

#from shield2:
#/gps/pos/centre 0.2 0.1 0. m
#/gps/pos/halfx 1.401 m 
#/gps/pos/halfy 1.001 m
#/gps/pos/halfz 1.051 m

#from shield3:
#/gps/pos/centre 0.2 0.1 0. m
#/gps/pos/halfx 0.851 m 
#/gps/pos/halfy 0.476 m
#/gps/pos/halfz 0.476 m

#from airbox:
/gps/pos/centre 0.08 0.05 0. m
/gps/pos/halfx 0.551 m 
/gps/pos/halfy 0.301 m
/gps/pos/halfz 0.276 m

# set the focusing point, default is (0, 0, 0)
#/gps/ang/type iso


/gps/ene/type User
/gps/hist/type energy
##FIXME: check normalization
#######      energy[MeV]  n/keV/cm2
/gps/hist/point 0	0
/gps/hist/point 0.001	12761
/gps/hist/point 0.005	608
/gps/hist/point 0.01	347
/gps/hist/point 0.03	801
/gps/hist/point 0.05	509
/gps/hist/point 0.1	982
/gps/hist/point 0.5	4901
/gps/hist/point 1	2795
/gps/hist/point 2	1656
/gps/hist/point 3	514
/gps/hist/point 4	212
/gps/hist/point 6	182
/gps/hist/point 10	5
/gps/hist/point 50	1
/gps/hist/point 100	1
/gps/hist/point 200	2
/gps/hist/point 300	0
/gps/hist/point 400	0
/gps/hist/point 500	0
/gps/hist/point 1000	0
/gps/hist/point 2000	0

/gps/ang/type user

/gps/hist/type theta
/gps/hist/point 0	0
/gps/hist/point 0.1309	99
/gps/hist/point 0.261799	321
/gps/hist/point 0.392699	568
/gps/hist/point 0.523599	824
/gps/hist/point 0.654498	1074
/gps/hist/point 0.785398	1215
/gps/hist/point 0.916298	1417
/gps/hist/point 1.0472	1476
/gps/hist/point 1.1781	1583
/gps/hist/point 1.309	1585
/gps/hist/point 1.4399	1538
/gps/hist/point 1.5708	1404
/gps/hist/point 1.7017	1405
/gps/hist/point 1.8326	1488
/gps/hist/point 1.9635	1620
/gps/hist/point 2.0944	1609
/gps/hist/point 2.22529	1472
/gps/hist/point 2.35619	1428
/gps/hist/point 2.48709	1318
/gps/hist/point 2.61799	1066
/gps/hist/point 2.74889	798
/gps/hist/point 2.87979	559
/gps/hist/point 3.01069	304
/gps/hist/point 3.14159	106

/gps/hist/type phi
/gps/hist/point 0	0
/gps/hist/point 0.261799	938
/gps/hist/point 0.523599	1034
/gps/hist/point 0.785398	1141
/gps/hist/point 1.0472	1222
/gps/hist/point 1.309	1199
/gps/hist/point 1.5708	1186
/gps/hist/point 1.8326	1159
/gps/hist/point 2.0944	1222
/gps/hist/point 2.35619	1127
/gps/hist/point 2.61799	1084
/gps/hist/point 2.87979	1054
/gps/hist/point 3.14159	912
/gps/hist/point 3.40339	874
/gps/hist/point 3.66519	976
/gps/hist/point 3.92699	1066
/gps/hist/point 4.18879	1195
/gps/hist/point 4.45059	1133
/gps/hist/point 4.71239	1110
/gps/hist/point 4.97419	1133
/gps/hist/point 5.23599	1228
/gps/hist/point 5.49779	1148
/gps/hist/point 5.75959	1164
/gps/hist/point 6.02139	1076
/gps/hist/point 6.28319	896


#Save only events that pass that have hits in the sensitive gas
/CYGNO/cutoutfile 1
/CYGNO/save_hits_branches 1
/CYGNO/registeron 0
#
/run/initialize
#change these for debug
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/CYGNO/reportingfrequency 1000
#Output file name
/CYGNO/outfile ext_neutron_test
/random/setSeeds 575841909 838392975
#/process/em/deexcitationIgnoreCut true

# define number of events to be generated
/run/beamOn 100000
