# python scripts/submit_jobs_cygno-login.py -n 1000 -e 1000   --builddir  /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork-build/ --tmpdir /nfs/cygno/users/dimperig/CYGNO/CYGNO-tmp/ --codedir /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork/ --outdir /nfs/cygno2/CYGNO-MC-data/ -m CYGNO_60_40_He_1_keVee --tag CYGNO_60_40_He_1_keVee
# python scripts/submit_jobs_cygno-login.py -n 1000 -e 1000   --builddir  /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork-build/ --tmpdir /nfs/cygno/users/dimperig/CYGNO/CYGNO-tmp/ --codedir /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork/ --outdir /nfs/cygno2/CYGNO-MC-data/ -m CYGNO_60_40_He_3_keVee --tag CYGNO_60_40_He_3_keVee
# python scripts/submit_jobs_cygno-login.py -n 1000 -e 1000   --builddir  /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork-build/ --tmpdir /nfs/cygno/users/dimperig/CYGNO/CYGNO-tmp/ --codedir /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork/ --outdir /nfs/cygno2/CYGNO-MC-data/ -m CYGNO_60_40_He_5_keVee --tag CYGNO_60_40_He_5_keVee
# python scripts/submit_jobs_cygno-login.py -n 1000 -e 1000   --builddir  /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork-build/ --tmpdir /nfs/cygno/users/dimperig/CYGNO/CYGNO-tmp/ --codedir /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork/ --outdir /nfs/cygno2/CYGNO-MC-data/ -m CYGNO_60_40_He_10_keVee --tag CYGNO_60_40_He_10_keVee
# python scripts/submit_jobs_cygno-login.py -n 1000 -e 1000   --builddir  /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork-build/ --tmpdir /nfs/cygno/users/dimperig/CYGNO/CYGNO-tmp/ --codedir /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork/ --outdir /nfs/cygno2/CYGNO-MC-data/ -m CYGNO_60_40_He_15_keVee --tag CYGNO_60_40_He_15_keVee
# python scripts/submit_jobs_cygno-login.py -n 1000 -e 1000   --builddir  /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork-build/ --tmpdir /nfs/cygno/users/dimperig/CYGNO/CYGNO-tmp/ --codedir /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork/ --outdir /nfs/cygno2/CYGNO-MC-data/ -m CYGNO_60_40_He_20_keVee --tag CYGNO_60_40_He_20_keVee
# python scripts/submit_jobs_cygno-login.py -n 1000 -e 1000   --builddir  /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork-build/ --tmpdir /nfs/cygno/users/dimperig/CYGNO/CYGNO-tmp/ --codedir /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork/ --outdir /nfs/cygno2/CYGNO-MC-data/ -m CYGNO_60_40_He_25_keVee --tag CYGNO_60_40_He_25_keVee
# python scripts/submit_jobs_cygno-login.py -n 1000 -e 1000   --builddir  /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork-build/ --tmpdir /nfs/cygno/users/dimperig/CYGNO/CYGNO-tmp/ --codedir /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork/ --outdir /nfs/cygno2/CYGNO-MC-data/ -m CYGNO_60_40_He_30_keVee --tag CYGNO_60_40_He_30_keVee
# python scripts/submit_jobs_cygno-login.py -n 1000 -e 1000   --builddir  /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork-build/ --tmpdir /nfs/cygno/users/dimperig/CYGNO/CYGNO-tmp/ --codedir /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork/ --outdir /nfs/cygno2/CYGNO-MC-data/ -m CYGNO_60_40_He_35_keVee --tag CYGNO_60_40_He_35_keVee
# python scripts/submit_jobs_cygno-login.py -n 1000 -e 1000   --builddir  /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork-build/ --tmpdir /nfs/cygno/users/dimperig/CYGNO/CYGNO-tmp/ --codedir /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork/ --outdir /nfs/cygno2/CYGNO-MC-data/ -m CYGNO_60_40_He_40_keVee --tag CYGNO_60_40_He_40_keVee
# python scripts/submit_jobs_cygno-login.py -n 1000 -e 1000   --builddir  /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork-build/ --tmpdir /nfs/cygno/users/dimperig/CYGNO/CYGNO-tmp/ --codedir /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork/ --outdir /nfs/cygno2/CYGNO-MC-data/ -m CYGNO_60_40_He_45_keVee --tag CYGNO_60_40_He_45_keVee
# python scripts/submit_jobs_cygno-login.py -n 1000 -e 1000   --builddir  /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork-build/ --tmpdir /nfs/cygno/users/dimperig/CYGNO/CYGNO-tmp/ --codedir /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork/ --outdir /nfs/cygno2/CYGNO-MC-data/ -m CYGNO_60_40_He_50_keVee --tag CYGNO_60_40_He_50_keVee
 python scripts/submit_jobs_cygno-login.py -n 1000 -e 1000   --builddir  /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork-build/ --tmpdir /nfs/cygno/users/dimperig/CYGNO/CYGNO-tmp/ --codedir /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork/ --outdir /nfs/cygno2/CYGNO-MC-data/ -m CYGNO_60_40_C_1_keVee --tag CYGNO_60_40_C_1_keVee
 python scripts/submit_jobs_cygno-login.py -n 1000 -e 1000   --builddir  /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork-build/ --tmpdir /nfs/cygno/users/dimperig/CYGNO/CYGNO-tmp/ --codedir /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork/ --outdir /nfs/cygno2/CYGNO-MC-data/ -m CYGNO_60_40_C_3_keVee --tag CYGNO_60_40_C_3_keVee
 python scripts/submit_jobs_cygno-login.py -n 1000 -e 1000   --builddir  /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork-build/ --tmpdir /nfs/cygno/users/dimperig/CYGNO/CYGNO-tmp/ --codedir /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork/ --outdir /nfs/cygno2/CYGNO-MC-data/ -m CYGNO_60_40_C_5_keVee --tag CYGNO_60_40_C_5_keVee
 python scripts/submit_jobs_cygno-login.py -n 1000 -e 1000   --builddir  /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork-build/ --tmpdir /nfs/cygno/users/dimperig/CYGNO/CYGNO-tmp/ --codedir /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork/ --outdir /nfs/cygno2/CYGNO-MC-data/ -m CYGNO_60_40_C_10_keVee --tag CYGNO_60_40_C_10_keVee
 python scripts/submit_jobs_cygno-login.py -n 1000 -e 1000   --builddir  /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork-build/ --tmpdir /nfs/cygno/users/dimperig/CYGNO/CYGNO-tmp/ --codedir /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork/ --outdir /nfs/cygno2/CYGNO-MC-data/ -m CYGNO_60_40_C_15_keVee --tag CYGNO_60_40_C_15_keVee
 python scripts/submit_jobs_cygno-login.py -n 1000 -e 1000   --builddir  /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork-build/ --tmpdir /nfs/cygno/users/dimperig/CYGNO/CYGNO-tmp/ --codedir /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork/ --outdir /nfs/cygno2/CYGNO-MC-data/ -m CYGNO_60_40_C_20_keVee --tag CYGNO_60_40_C_20_keVee
 python scripts/submit_jobs_cygno-login.py -n 1000 -e 1000   --builddir  /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork-build/ --tmpdir /nfs/cygno/users/dimperig/CYGNO/CYGNO-tmp/ --codedir /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork/ --outdir /nfs/cygno2/CYGNO-MC-data/ -m CYGNO_60_40_C_25_keVee --tag CYGNO_60_40_C_25_keVee
 python scripts/submit_jobs_cygno-login.py -n 1000 -e 1000   --builddir  /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork-build/ --tmpdir /nfs/cygno/users/dimperig/CYGNO/CYGNO-tmp/ --codedir /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork/ --outdir /nfs/cygno2/CYGNO-MC-data/ -m CYGNO_60_40_C_30_keVee --tag CYGNO_60_40_C_30_keVee
 python scripts/submit_jobs_cygno-login.py -n 1000 -e 1000   --builddir  /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork-build/ --tmpdir /nfs/cygno/users/dimperig/CYGNO/CYGNO-tmp/ --codedir /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork/ --outdir /nfs/cygno2/CYGNO-MC-data/ -m CYGNO_60_40_C_35_keVee --tag CYGNO_60_40_C_35_keVee
 python scripts/submit_jobs_cygno-login.py -n 1000 -e 1000   --builddir  /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork-build/ --tmpdir /nfs/cygno/users/dimperig/CYGNO/CYGNO-tmp/ --codedir /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork/ --outdir /nfs/cygno2/CYGNO-MC-data/ -m CYGNO_60_40_C_40_keVee --tag CYGNO_60_40_C_40_keVee
 python scripts/submit_jobs_cygno-login.py -n 1000 -e 1000   --builddir  /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork-build/ --tmpdir /nfs/cygno/users/dimperig/CYGNO/CYGNO-tmp/ --codedir /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork/ --outdir /nfs/cygno2/CYGNO-MC-data/ -m CYGNO_60_40_C_45_keVee --tag CYGNO_60_40_C_45_keVee
 python scripts/submit_jobs_cygno-login.py -n 1000 -e 1000   --builddir  /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork-build/ --tmpdir /nfs/cygno/users/dimperig/CYGNO/CYGNO-tmp/ --codedir /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork/ --outdir /nfs/cygno2/CYGNO-MC-data/ -m CYGNO_60_40_C_50_keVee --tag CYGNO_60_40_C_50_keVee
# python scripts/submit_jobs_cygno-login.py -n 1000 -e 1000   --builddir  /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork-build/ --tmpdir /nfs/cygno/users/dimperig/CYGNO/CYGNO-tmp/ --codedir /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork/ --outdir /nfs/cygno2/CYGNO-MC-data/ -m CYGNO_60_40_F_1_keVee --tag CYGNO_60_40_F_1_keVee
# python scripts/submit_jobs_cygno-login.py -n 1000 -e 1000   --builddir  /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork-build/ --tmpdir /nfs/cygno/users/dimperig/CYGNO/CYGNO-tmp/ --codedir /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork/ --outdir /nfs/cygno2/CYGNO-MC-data/ -m CYGNO_60_40_F_3_keVee --tag CYGNO_60_40_F_3_keVee
# python scripts/submit_jobs_cygno-login.py -n 1000 -e 1000   --builddir  /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork-build/ --tmpdir /nfs/cygno/users/dimperig/CYGNO/CYGNO-tmp/ --codedir /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork/ --outdir /nfs/cygno2/CYGNO-MC-data/ -m CYGNO_60_40_F_5_keVee --tag CYGNO_60_40_F_5_keVee
# python scripts/submit_jobs_cygno-login.py -n 1000 -e 1000   --builddir  /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork-build/ --tmpdir /nfs/cygno/users/dimperig/CYGNO/CYGNO-tmp/ --codedir /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork/ --outdir /nfs/cygno2/CYGNO-MC-data/ -m CYGNO_60_40_F_10_keVee --tag CYGNO_60_40_F_10_keVee
# python scripts/submit_jobs_cygno-login.py -n 1000 -e 1000   --builddir  /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork-build/ --tmpdir /nfs/cygno/users/dimperig/CYGNO/CYGNO-tmp/ --codedir /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork/ --outdir /nfs/cygno2/CYGNO-MC-data/ -m CYGNO_60_40_F_15_keVee --tag CYGNO_60_40_F_15_keVee
# python scripts/submit_jobs_cygno-login.py -n 1000 -e 1000   --builddir  /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork-build/ --tmpdir /nfs/cygno/users/dimperig/CYGNO/CYGNO-tmp/ --codedir /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork/ --outdir /nfs/cygno2/CYGNO-MC-data/ -m CYGNO_60_40_F_20_keVee --tag CYGNO_60_40_F_20_keVee
# python scripts/submit_jobs_cygno-login.py -n 1000 -e 1000   --builddir  /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork-build/ --tmpdir /nfs/cygno/users/dimperig/CYGNO/CYGNO-tmp/ --codedir /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork/ --outdir /nfs/cygno2/CYGNO-MC-data/ -m CYGNO_60_40_F_25_keVee --tag CYGNO_60_40_F_25_keVee
# python scripts/submit_jobs_cygno-login.py -n 1000 -e 1000   --builddir  /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork-build/ --tmpdir /nfs/cygno/users/dimperig/CYGNO/CYGNO-tmp/ --codedir /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork/ --outdir /nfs/cygno2/CYGNO-MC-data/ -m CYGNO_60_40_F_30_keVee --tag CYGNO_60_40_F_30_keVee
# python scripts/submit_jobs_cygno-login.py -n 1000 -e 1000   --builddir  /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork-build/ --tmpdir /nfs/cygno/users/dimperig/CYGNO/CYGNO-tmp/ --codedir /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork/ --outdir /nfs/cygno2/CYGNO-MC-data/ -m CYGNO_60_40_F_35_keVee --tag CYGNO_60_40_F_35_keVee
# python scripts/submit_jobs_cygno-login.py -n 1000 -e 1000   --builddir  /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork-build/ --tmpdir /nfs/cygno/users/dimperig/CYGNO/CYGNO-tmp/ --codedir /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork/ --outdir /nfs/cygno2/CYGNO-MC-data/ -m CYGNO_60_40_F_40_keVee --tag CYGNO_60_40_F_40_keVee
# python scripts/submit_jobs_cygno-login.py -n 1000 -e 1000   --builddir  /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork-build/ --tmpdir /nfs/cygno/users/dimperig/CYGNO/CYGNO-tmp/ --codedir /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork/ --outdir /nfs/cygno2/CYGNO-MC-data/ -m CYGNO_60_40_F_45_keVee --tag CYGNO_60_40_F_45_keVee
# python scripts/submit_jobs_cygno-login.py -n 1000 -e 1000   --builddir  /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork-build/ --tmpdir /nfs/cygno/users/dimperig/CYGNO/CYGNO-tmp/ --codedir /nfs/cygno/users/dimperig/CYGNO/CYGNO-MC-QF-myfork/ --outdir /nfs/cygno2/CYGNO-MC-data/ -m CYGNO_60_40_F_50_keVee --tag CYGNO_60_40_F_50_keVee
